### ISSUE TITLE
Error when i try to download solo torrent with multiple files  [sorry for my bad english]

### ISSUE THREAD

**Issue by ninshi78** [TouchTone/pyjsit#1]
yajsig.log:
http://textuploader.com/652k

Sorry i don't found "aria.log" in the soft folder.

it attached an image containing screenshot of different error message.
![sans titre](https://cloud.githubusercontent.com/assets/10376136/5600275/fdf1be8e-92d6-11e4-9708-f3eef242fb98.png)

Hoping to have you help. Thank you for your work!

**Comment by TouchTone** [comment]
Hi ninshi78,

can you try with the latest version (0.5.2)? I fixed a bunch of Unicode issues in it, and even though Unicode is a never-ending trove of problems it's possible that they are fixed now.

If not, can you please set the fileLogLevel in your preferences.json to 6 and run it again? That way I get a better idea what is wrong.

Thanks!

**Comment by TouchTone** [comment]
Haven't heard back in a month, assuming fixed.
