### ISSUE TITLE
 Issue with the new version of YAJSITG

### ISSUE THREAD

**Issue by Zero3K** [TouchTone/pyjsit#5]
It won't download the file of a torrent anymore. It just gets stuck at 99.5% checked.

**Comment by TouchTone** [comment]
Hm, can reproduce it. Quick fix: remove the "unpackArchives": "false" line from preferences.json. 

Still need to figure out what the real problem is.

**Comment by Zero3K** [comment]
Doing that didn't fix it for me.

**Comment by TouchTone** [comment]
I couldn't reproduce it any more, not sure what to do at this point. Sorry!
